# Basic Data Types in Python


### Basic Data Types


In [3]:
#integer
x=4
x?
x

4

In [19]:
#string
x='Hello'
x?
x

'Hello'

In [21]:
#list of integers (note that the index is starting at position 0, not 1)
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
type(L[0])

int

In [25]:
#list of strings
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [27]:
type(L2[0])

str

In [29]:
#heterogenous list
L3 = [True, "2", 3.0, 4]
L3

[True, '2', 3.0, 4]

In [30]:
[type(item) for item in L3]

[bool, str, float, int]


### Basics of NumPy Arrays
NumPy arrays form the core of nearly all data science tools in Python.

In [2]:
import numpy as np

How to get more information about the NumPy-Package as well as the different functions?

In [ ]:
#Documentation
np?

In [ ]:
#TAB-Completion
np.

In [40]:
# integer array:
np.array([1, 4, 10, 5, 1])

array([ 1,  4, 10,  5,  1])

In [41]:
#all elements of an array need to have the same type (if not, they are up-cast):
np.array([3.14, 5, 2, 3])

array([3.14, 5.  , 2.  , 3.  ])

In [39]:
#explicitly set the data type of a resulting array with dtype
np.array([1, 2, 3], dtype='float32')

array([1., 2., 3.], dtype=float32)

In [43]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 5) for i in [2, 4, 6]])

array([[ 2,  3,  4,  5,  6],
       [ 4,  5,  6,  7,  8],
       [ 6,  7,  8,  9, 10]])

In [ ]:
Builtin routines:

In [45]:
# Create a length-20 integer array filled with zeros
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
# Create a 3x4 floating-point array filled with ones
np.ones((3, 4), dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
# Create a 4x4 identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
# Create a 3x4 array filled with 3.14
np.full((3, 4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [52]:
# Create an array filled with a linear sequence with 0<=x<24 stepping by 2
np.arange(0, 24, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [54]:
# Create an array of 7 values evenly spaced between 0 and 1
np.linspace(0, 1, 7)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [61]:
# Create a 2x4 array of uniformly distributed
# random values between 0 and 1
np.random.random((2, 4))

array([[0.52093186, 0.35928117, 0.64849451, 0.07978291],
       [0.11299924, 0.26276262, 0.6431791 , 0.02018053]])

In [62]:
# Create a 2x4 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (2, 4))

array([[-0.69477276,  0.30927777,  1.03056001, -0.43594335],
       [ 1.83936908,  0.82117114,  0.94815475, -0.80583525]])

In [64]:
# Create a 2x4 array of random integers in the interval [0, 20)
np.random.randint(0, 20, (2, 4))

array([[ 3, 17, 13, 11],
       [16, 15,  3,  6]])