# Basics of NumPy Array Manipulation

### Attributes

In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array):

In [6]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
x3

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

# ##Array Indexing: Accessing Single Elements

In [8]:
x1

array([5, 0, 3, 3, 7, 9])

In [9]:
x1[0]

5

In [10]:
x1[4]

7

In [11]:
#use negative indices to access from the end
x1[-1]

9

In [13]:
x1[-3]

3

In [14]:
#In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [15]:
x2[0, 1]

5

In [16]:
x2[2,-1]

7

### Array slicing x[start:stop:step]

In [17]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#first five elements (starting at 0 and ending before 5)
x[0:5:1]

array([0, 1, 2, 3, 4])

In [19]:
#easier
x[:5]

array([0, 1, 2, 3, 4])

In [20]:
#elements starting at index 5
x[5:]

array([5, 6, 7, 8, 9])

In [21]:
#indices starting at 4 and ending before 7
x[4:7]

array([4, 5, 6])

In [22]:
#every second element
x[::2]

array([0, 2, 4, 6, 8])

In [23]:
#  every third element, starting at index 1
x[1::3]

array([1, 4, 7])

In [24]:
# all elements, reversed
x[::-1]  

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Multi-dimensional sub-arrays 

In [25]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [28]:
x2[:2, :3]  # two rows (starting at zero ending before 2), three columns (starting at zero ending before 3)

array([[3, 5, 2],
       [7, 6, 8]])

In [29]:
x2[:3, ::2]  # all rows, every second column

array([[3, 2],
       [7, 8],
       [1, 7]])

In [30]:
#reversed
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [31]:
# first column
x2[:,0]

array([3, 7, 1])

In [34]:
#second row
x2[1,:]

array([7, 6, 8, 8])

### Subarrays as no-copy views 

In [35]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [36]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [37]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [38]:
print(x2) #the original array has also changed! it means that we can access and process pieces datasets 
#without the need to copy the underlying data buffer.

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Creating copies of arrays

In [39]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [40]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [41]:
print(x2)#the original array has not changed!

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Reshaping of Arrays

In [43]:
np.arange(1, 10)
print(grid)

[1 2 3 4 5 6 7 8 9]


In [44]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Array Concatenation and Splitting 

In [47]:
x = np.array([1, 2, 3])
y = np.array([10, 11, 12])
np.concatenate([x, y])

array([ 1,  2,  3, 10, 11, 12])

In [48]:
#concatenate more than two arrays at once
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3 10 11 12 99 99 99]


In [50]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [51]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [52]:
#splitting
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [53]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
